/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2lab_josepereira;

import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author j0c3lwiz
 */
public class atm extends javax.swing.JFrame {

    /**
     * Creates new form atm
     */
    public atm() {
        initComponents();
        wombo_combo();
    }
    static int auxiliar = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prinic = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crear_user = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        cu_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cu_pnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cu_segudonombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cu_papellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cu_anaci = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cu_anoafil = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_c = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cu_contra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cu_segundoapel = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        crear_atm = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ca_ubicacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ca_id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ca_mante = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        sp_ano = new javax.swing.JSpinner();
        ste_100 = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ste_500 = new javax.swing.JSpinner();
        atmbb = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        tf_atm_nombre = new javax.swing.JLabel();
        tf_atm_ubicacion = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_cor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        trances = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tf_princinombre = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_princiid = new javax.swing.JLabel();
        tf_princiid1 = new javax.swing.JLabel();
        depositos = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        quinientos = new javax.swing.JComboBox<>();
        cienas = new javax.swing.JComboBox<>();
        cuenta_cb = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        retiros = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        quinientos1 = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cien1 = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        cuenta_cb1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        Manager = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jl_manager = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sp_manager_100 = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        sp_manager500 = new javax.swing.JSpinner();
        jButton16 = new javax.swing.JButton();
        wombo_manager = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        wombo_combo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("Entrar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("ATM");

        javax.swing.GroupLayout prinicLayout = new javax.swing.GroupLayout(prinic.getContentPane());
        prinic.getContentPane().setLayout(prinicLayout);
        prinicLayout.setHorizontalGroup(
            prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prinicLayout.createSequentialGroup()
                .addGroup(prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prinicLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel3))
                    .addGroup(prinicLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(prinicLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        prinicLayout.setVerticalGroup(
            prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prinicLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(prinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
        );

        jLabel6.setText("ID");

        jLabel7.setText("Primer Nombre");

        jLabel8.setText("Segundo Nombre");

        jLabel9.setText("Primer Apellido");

        jLabel10.setText("Ano de Nacimiento");

        jLabel11.setText("MM/DD/AA");

        jLabel12.setText("Ano de Afiliacion");

        jLabel13.setText("MM/DD/AA");

        buttonGroup1.add(rb_m);
        rb_m.setSelected(true);
        rb_m.setText("Usuario Mantenimiento");

        buttonGroup1.add(rb_c);
        rb_c.setText("Usuario Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Crear Usuario");

        jButton5.setText("Crear Usuario");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel5.setText("Contra");

        jLabel14.setText("Segundo Apellido");

        javax.swing.GroupLayout crear_userLayout = new javax.swing.GroupLayout(crear_user.getContentPane());
        crear_user.getContentPane().setLayout(crear_userLayout);
        crear_userLayout.setHorizontalGroup(
            crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_userLayout.createSequentialGroup()
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_userLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crear_userLayout.createSequentialGroup()
                                .addComponent(rb_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_c))
                            .addGroup(crear_userLayout.createSequentialGroup()
                                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crear_userLayout.createSequentialGroup()
                                        .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cu_id)
                                            .addComponent(cu_pnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crear_userLayout.createSequentialGroup()
                                        .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cu_papellido)
                                            .addComponent(cu_contra))))
                                .addGap(80, 80, 80)
                                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(crear_userLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cu_anaci, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel11))
                                        .addGroup(crear_userLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cu_anoafil, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel13)))
                                    .addGroup(crear_userLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(cu_segudonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crear_userLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(cu_segundoapel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(crear_userLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel4))
                    .addGroup(crear_userLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jButton5)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        crear_userLayout.setVerticalGroup(
            crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_userLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(76, 76, 76)
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cu_anaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cu_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cu_anoafil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cu_segudonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cu_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cu_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cu_segundoapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_m)
                    .addComponent(rb_c))
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addGap(27, 27, 27))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Crear ATM");

        jLabel16.setText("Ubicacion del ATM");

        jLabel17.setText("ID(unico)");

        jLabel18.setText("Año Fabricacion");

        jLabel19.setText("Mantenimiento");

        ca_mante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Semestral" }));

        jButton6.setText("Crear ATM");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        sp_ano.setModel(new javax.swing.SpinnerNumberModel(2000, 1000, null, 1));

        jLabel35.setText("Billetes de 100");

        jLabel36.setText("Billetes de 500");

        javax.swing.GroupLayout crear_atmLayout = new javax.swing.GroupLayout(crear_atm.getContentPane());
        crear_atm.getContentPane().setLayout(crear_atmLayout);
        crear_atmLayout.setHorizontalGroup(
            crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_atmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_atmLayout.createSequentialGroup()
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ca_ubicacion)
                            .addComponent(ca_id)
                            .addComponent(ca_mante, 0, 251, Short.MAX_VALUE))
                        .addGap(135, 135, 135)
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ste_100, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crear_atmLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(ste_500, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_atmLayout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(84, 84, 84))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_atmLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(84, 84, 84))))
                    .addComponent(sp_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_atmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(368, 368, 368))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_atmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(328, 328, 328))
        );
        crear_atmLayout.setVerticalGroup(
            crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_atmLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(66, 66, 66)
                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_atmLayout.createSequentialGroup()
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ca_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(ca_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crear_atmLayout.createSequentialGroup()
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ste_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(46, 46, 46)
                        .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ste_500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))))
                .addGap(52, 52, 52)
                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sp_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ca_mante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(28, 28, 28))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setText("Bienvenido al ATM Cajero :");

        tf_atm_nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_atm_nombre.setText("jLabel21");

        tf_atm_ubicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_atm_ubicacion.setText("jLabel21");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Ubicado en:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Usuario");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Contraseña");

        jButton7.setText("Entrar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout atmbbLayout = new javax.swing.GroupLayout(atmbb.getContentPane());
        atmbb.getContentPane().setLayout(atmbbLayout);
        atmbbLayout.setHorizontalGroup(
            atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atmbbLayout.createSequentialGroup()
                .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atmbbLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(atmbbLayout.createSequentialGroup()
                                .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(43, 43, 43)
                                .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(atmbbLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_atm_ubicacion))
                            .addComponent(tf_atm_nombre)
                            .addComponent(jLabel20)))
                    .addGroup(atmbbLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton7)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        atmbbLayout.setVerticalGroup(
            atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atmbbLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_atm_nombre)
                .addGap(20, 20, 20)
                .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(atmbbLayout.createSequentialGroup()
                        .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tf_atm_ubicacion))
                        .addGap(77, 77, 77)
                        .addGroup(atmbbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tf_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel24))
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(68, 68, 68))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton8.setText("Realizar Depositos");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
        });

        jButton9.setText("Revisar Transacciones");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Crear Cuenta");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Estado de Cuenta(Saldo)");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("Realizar Retiros");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("Exit");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Bienvenido");

        tf_princinombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_princinombre.setText("dd");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("ID");

        tf_princiid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_princiid.setText("ID");

        tf_princiid1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_princiid1.setText("Que Desea Realizar?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(tf_princinombre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_princiid1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(tf_princiid)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_princinombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_princiid))
                .addGap(35, 35, 35)
                .addComponent(tf_princiid1)
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout trancesLayout = new javax.swing.GroupLayout(trances.getContentPane());
        trances.getContentPane().setLayout(trancesLayout);
        trancesLayout.setHorizontalGroup(
            trancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trancesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        trancesLayout.setVerticalGroup(
            trancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trancesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel25.setText("Depositos");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("500 Lps");

        jLabel28.setText("100 Lps");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Ingrese la cantidad de billetes de 500 y 100 :");

        jButton14.setText("Depositar");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jLabel37.setText("Max");

        max.setText("jLabel38");

        jLabel38.setText("Max");

        min.setText("jLabel38");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(quinientos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(max))
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(min)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cienas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel29)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(min)
                            .addComponent(cienas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(max)
                            .addComponent(quinientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );

        jLabel30.setText("Cuenta");

        javax.swing.GroupLayout depositosLayout = new javax.swing.GroupLayout(depositos.getContentPane());
        depositos.getContentPane().setLayout(depositosLayout);
        depositosLayout.setHorizontalGroup(
            depositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositosLayout.createSequentialGroup()
                .addGroup(depositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(depositosLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(depositosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(cuenta_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        depositosLayout.setVerticalGroup(
            depositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(depositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuenta_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        quinientos1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel31.setText("500 Lps");

        jLabel32.setText("100 Lps");

        cien1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Ingrese la cantidad de billetes de 500 y 100 :");

        jButton15.setText("Retirar");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(quinientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(cuenta_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cien1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel33)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel33)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quinientos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuenta_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addGap(42, 42, 42))
        );

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText("Retiros");

        javax.swing.GroupLayout retirosLayout = new javax.swing.GroupLayout(retiros.getContentPane());
        retiros.getContentPane().setLayout(retirosLayout);
        retirosLayout.setHorizontalGroup(
            retirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retirosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(retirosLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        retirosLayout.setVerticalGroup(
            retirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, retirosLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel39.setText("Bienvenido");

        jl_manager.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jl_manager.setText("user");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel41.setText("100");

        jLabel40.setText("500");

        jButton16.setText("Ingresar Dinero");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_manager500, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_manager_100, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(44, 44, 44))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(wombo_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wombo_manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_manager500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_manager_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );

        javax.swing.GroupLayout ManagerLayout = new javax.swing.GroupLayout(Manager.getContentPane());
        Manager.getContentPane().setLayout(ManagerLayout);
        ManagerLayout.setHorizontalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addGroup(ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_manager))
                    .addGroup(ManagerLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        ManagerLayout.setVerticalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jl_manager))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Crear Usuario");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Crear ATM");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jButton4.setText("Seleccionar ATM");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(wombo_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(wombo_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton4)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            administrador_binario ap = new administrador_binario("./Users.diegobb");
            ap.cargarArchivo();
            //String Id, String primer_nombre, String segundo_nombre, String primer_apellido, String contra, String segundo_apellido, String ano_naci, String ano_afiliacion
            String Id = cu_id.getText();
            String primer_nombre = cu_pnombre.getText();
            String segundo_nombre = cu_segudonombre.getText();
            String primer_apellido = cu_papellido.getText();
            String contra = cu_contra.getText();
            String segundo_apellido = cu_segundoapel.getText();
            String ano_naci = cu_anaci.getText();
            String ano_afil = cu_anoafil.getText();
            if (rb_c.isSelected()) {
                ap.getListausuarios().add(new usuario_cliente(Id, primer_nombre, segundo_nombre, primer_apellido, contra, segundo_apellido, ano_naci, ano_afil));
                ap.escribir();
                JOptionPane.showMessageDialog(this, "Usuario Cliente creado CORRECTAMENTE");
                wombo_combo();
            } else if (rb_m.isSelected()) {
                ap.getListausuarios().add(new usuario_mantenimiento(Id, primer_nombre, segundo_nombre, primer_apellido, contra, segundo_apellido, ano_naci, ano_afil));
                ap.escribir();
                JOptionPane.showMessageDialog(this, "Usuario Mantenimiento creado CORRECTAMENTE");
                wombo_combo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Porfavor Ingrese Datos Validos!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        crear_user.setModal(true);
        crear_user.pack();
        crear_user.setLocationRelativeTo(this);
        crear_user.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        crear_atm.setModal(true);
        crear_atm.pack();
        crear_atm.setLocationRelativeTo(this);
        crear_atm.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        //String Ubicacion, String Id_unico, int ano_fabri, String mantenimineto
        try {
            administrador_binario_atm ap = new administrador_binario_atm("./ATM.diegobb");
            ap.cargarArchivo();
            String ubicacion = ca_ubicacion.getText();
            String id_uni = ca_id.getText();
            int ano = (int) sp_ano.getValue();
            String mantenimiento = ca_mante.getSelectedItem().toString();
            int aux = 0;
            for (atma o : ap.getLista_atms()) {
                if (o.getId_unico().toString().equals(id_uni)) {
                    aux = 1;
                }
            }
            if (aux == 1) {
                JOptionPane.showMessageDialog(this, "El ID ya esta registrado");
            } else if (aux == 0) {
                int e = (int) ste_100.getValue();
                int e2 = (int) ste_500.getValue();
                ap.getLista_atms().add(new atma(ubicacion, id_uni, ano, mantenimiento, e2, e));
                ap.escribir();
                JOptionPane.showMessageDialog(this, "ATM Creado correctamente");
                wombo_combo();
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        auxiliar = 0;
        DefaultComboBoxModel mod = (DefaultComboBoxModel) wombo_combo.getModel();
        atma temp_atm = (atma) mod.getSelectedItem();
        pos_atm = wombo_combo.getSelectedIndex();
        tf_atm_nombre.setText(temp_atm.getId_unico().toString());
        tf_atm_ubicacion.setText(temp_atm.getUbicacion().toString());
        atmbb.setModal(true);
        atmbb.pack();
        atmbb.setLocationRelativeTo(this);
        atmbb.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        String error = "";

        try {
            administrador_binario ap = new administrador_binario("./Users.diegobb");
            ap.cargarArchivo();
            for (int i = 0; i < ap.getListausuarios().size(); i++) {
                if (tf_cor.getText().equals(ap.getListausuarios().get(i).getId()) && tf_contra.getText().equals(ap.getListausuarios().get(i).getContra())) {
                    pos_usu = i;
                }
            }

            //(inicio sesión, fallos*, cantidad de dinero retirado, cantidad de dinero ingresado) 
            //System.out.println(ap.getListausuarios().get(0).getId());
            //System.out.println(ap.getListausuarios().get(0).getContra());
            int aux = 0;
            for (Usuario u : ap.getListausuarios()) {
                if (tf_cor.getText().equals(u.getId()) && tf_contra.getText().equals(u.getContra())) {
                    if (u instanceof usuario_cliente) {
                        actualw = u;
                        tf_princiid.setText(u.getId().toString());
                        tf_princinombre.setText(u.getPrimer_apellido() + " , " + u.getPrimer_nombre() + " " + u.getSegundo_nombre());
                        Date fe = new Date();
                        Date ho = new Date();
                        String Descripcion = "Inicio sesion: " + actualw.getId();
                        atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
                        JOptionPane.showMessageDialog(this, "Se agrego un Log");
                        atm.escribir();
                        trances.setModal(true);
                        trances.pack();
                        trances.setLocationRelativeTo(this);
                        trances.setVisible(true);
                        aux = 1;
                    } else {
                        actualw = u;
                        DefaultComboBoxModel m = (DefaultComboBoxModel) wombo_manager.getModel();
                        m.removeAllElements();
                        for (int i = 0; i < atm.getLista_atms().size(); i++) {
                            m.addElement(atm.getLista_atms().get(i));
                        }
                    }
                }
            }

            System.out.println("dddddddddddd " + pos_usu);
            if (aux == 0) {
                JOptionPane.showMessageDialog(this, "El usuario y/o contrasena no son correctos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
            Date fe = new Date();
            Date ho = new Date();
            error = e.getMessage();
            String Descripcion = "Error: " + error;
            atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
            atm.escribir();
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        int cien = atm.getLista_atms().get(pos_atm).getCant_100();
        int qui = atm.getLista_atms().get(pos_atm).getCant_500();
        int c1 = cien / 100;
        int q1 = qui / 100;
        DefaultComboBoxModel cie = (DefaultComboBoxModel) cienas.getModel();
        DefaultComboBoxModel qw = (DefaultComboBoxModel) quinientos.getModel();
        cie.removeAllElements();
        qw.removeAllElements();
        for (int i = 1; i < cien + 1; i++) {
            cie.addElement(i);
        }
        for (int i = 1; i < qui + 1; i++) {
            qw.addElement(i);
        }
        //cienas.setModel(cie);
        //quinientos.setModel(qw);
        min.setText(String.valueOf(cien));
        max.setText(String.valueOf(qui));
        DefaultComboBoxModel mod = (DefaultComboBoxModel) cuenta_cb.getModel();
        mod.removeAllElements();
        for (int i = 0; i < ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().size(); i++) {
            mod.addElement(((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(i));
        }
        depositos.setModal(true);
        depositos.pack();
        depositos.setLocationRelativeTo(this);
        depositos.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        pos_cuenta = cuenta_cb.getSelectedIndex();
        String error = "";
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        try {

            if (((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No tiene cuentas!");
            } else {
                Date fe = new Date();
                Date ho = new Date();
                int antes = ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(pos_cuenta).getSaldo_disponible();
                int q = (int) quinientos.getSelectedItem() * 500;
                int c = (int) cienas.getSelectedItem() * 100;
                int tot = q + c + antes;
                ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(pos_cuenta).setSaldo_disponible(tot);
                ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getTransacciones().add(new trans(actualw.getId(), "Deposito :" + tot, fe, ho.getHours() + ":" + ho.getMinutes()));
                int t = (int) quinientos.getSelectedItem();
                int y = (int) cienas.getSelectedItem();
                atm.getLista_atms().get(pos_atm).setCant_100(atm.getLista_atms().get(pos_atm).getCant_100() - y);
                atm.getLista_atms().get(pos_atm).setCant_500(atm.getLista_atms().get(pos_atm).getCant_500() - t);
                ap.escribir();
                String Descripcion = "Depositado : " + tot;
                atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
                atm.escribir();
                JOptionPane.showMessageDialog(this, "Depositado Correctamente!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
            Date fe = new Date();
            Date ho = new Date();
            error = e.getMessage();
            String Descripcion = "Error: " + error;
            atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
            atm.escribir();

        }

    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        String acum = "";
        int aux = 1;
        for (int i = 0; i < ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getTransacciones().size(); i++) {
            acum += aux + ") " + ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getTransacciones().get(i) + "\n";
            aux++;
        }
        JOptionPane.showMessageDialog(this, acum);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        String g2 = JOptionPane.showInputDialog(this, "Ingrese el nombre de la Cuenta");
        Cuenta g = new Cuenta(g2);
        g.setPropietario(actualw);
        g.setSaldo_disponible(0);
        g.setId_usuario(actualw.getId());
        ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().add(g);
        ap.escribir();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        try {
            administrador_binario ap = new administrador_binario("./Users.diegobb");
            ap.cargarArchivo();
            String acums = "";
            int uxi = 1;
            for (int i = 0; i < ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().size(); i++) {
                acums += uxi + ") " + ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(i).getNumero_cuenta() + " Saldo" + ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(i).getSaldo_disponible() + "\n";
            }
            JOptionPane.showMessageDialog(this, "Saldo Disponible:\n " + acums);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
            Date fe = new Date();
            Date ho = new Date();
            String error = e.getMessage();
            String Descripcion = "Error: " + error;
            atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
            atm.escribir();
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        DefaultComboBoxModel mod = (DefaultComboBoxModel) cuenta_cb1.getModel();
        mod.removeAllElements();
        for (int i = 0; i < ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().size(); i++) {
            mod.addElement(((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(i));
        }
        retiros.setModal(true);
        retiros.pack();
        retiros.setLocationRelativeTo(this);
        retiros.setVisible(true);

    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        administrador_binario ap = new administrador_binario("./Users.diegobb");
        ap.cargarArchivo();
        pos_cuenta2 = cuenta_cb1.getSelectedIndex();
        String error = "";
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        try {
            if (((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No tiene cuentas!");
            } else {
                Date fe = new Date();
                Date ho = new Date();
                int antes = ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(pos_cuenta2).getSaldo_disponible();
                int q = (int) quinientos1.getValue() * 500;
                int c = (int) cien1.getValue() * 100;
                int tot = antes - (q + c);
                if (tot < 0) {
                    JOptionPane.showMessageDialog(this, "Error!");
                    Date fe2 = new Date();
                    Date ho2 = new Date();
                    error = "No puede tener menos que 0 en su cuenta";
                    String Descripcion = "Error: " + error;
                    atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe2, ho2.getHours() + ":" + ho2.getMinutes()));
                    atm.escribir();
                } else {
                    ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getCuentas().get(pos_cuenta2).setSaldo_disponible(tot);
                    ((usuario_cliente) ap.getListausuarios().get(pos_usu)).getTransacciones().add(new trans(actualw.getId(), "Retirado :" + tot, fe, ho.getHours() + ":" + ho.getMinutes()));
                    ap.escribir();
                    String Descripcion = "Retirado : " + tot;
                    atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
                    atm.escribir();
                    JOptionPane.showMessageDialog(this, "Retirado Correctamente!");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
            Date fe = new Date();
            Date ho = new Date();
            error = e.getMessage();
            String Descripcion = "Error: " + error;
            atm.getLista_atms().get(pos_atm).getLogs().add(new log_sistema(actualw.getId().toString(), Descripcion, fe, ho.getHours() + ":" + ho.getMinutes()));
            atm.escribir();

        }
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        administrador_binario_atm atm = new administrador_binario_atm("./ATM.diegobb");
        atm.cargarArchivo();
        pos_manager=wombo_manager.getSelectedIndex();
        int po=(int)sp_manager_100.getValue();
        int po2=(int)sp_manager500.getValue();
        atm.getLista_atms().get(pos_manager).setCant_100(atm.getLista_atms().get(pos_manager).getCant_100()+po);
        atm.getLista_atms().get(pos_manager).setCant_500(atm.getLista_atms().get(pos_manager).getCant_500()+po2);
    }//GEN-LAST:event_jButton16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Manager;
    private javax.swing.JDialog atmbb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ca_id;
    private javax.swing.JComboBox<String> ca_mante;
    private javax.swing.JTextField ca_ubicacion;
    private javax.swing.JSpinner cien1;
    private javax.swing.JComboBox<String> cienas;
    private javax.swing.JDialog crear_atm;
    private javax.swing.JDialog crear_user;
    private javax.swing.JTextField cu_anaci;
    private javax.swing.JTextField cu_anoafil;
    private javax.swing.JTextField cu_contra;
    private javax.swing.JTextField cu_id;
    private javax.swing.JTextField cu_papellido;
    private javax.swing.JTextField cu_pnombre;
    private javax.swing.JTextField cu_segudonombre;
    private javax.swing.JTextField cu_segundoapel;
    private javax.swing.JComboBox<String> cuenta_cb;
    private javax.swing.JComboBox<String> cuenta_cb1;
    private javax.swing.JDialog depositos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jl_manager;
    private javax.swing.JLabel max;
    private javax.swing.JLabel min;
    private javax.swing.JDialog prinic;
    private javax.swing.JComboBox<String> quinientos;
    private javax.swing.JSpinner quinientos1;
    private javax.swing.JRadioButton rb_c;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JDialog retiros;
    private javax.swing.JSpinner sp_ano;
    private javax.swing.JSpinner sp_manager500;
    private javax.swing.JSpinner sp_manager_100;
    private javax.swing.JSpinner ste_100;
    private javax.swing.JSpinner ste_500;
    private javax.swing.JLabel tf_atm_nombre;
    private javax.swing.JLabel tf_atm_ubicacion;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_cor;
    private javax.swing.JLabel tf_princiid;
    private javax.swing.JLabel tf_princiid1;
    private javax.swing.JLabel tf_princinombre;
    private javax.swing.JDialog trances;
    private javax.swing.JComboBox<String> wombo_combo;
    private javax.swing.JComboBox<String> wombo_manager;
    // End of variables declaration//GEN-END:variables
Usuario actualw = null;
    int pos_atm = -1;
    int pos_usu = -1;
    int pos_cuenta = -1;
    int pos_cuenta2 = -1;
    int pos_manager = -1;

    public void wombo_combo() {
        administrador_binario_atm ap = new administrador_binario_atm("./ATM.diegobb");
        ap.cargarArchivo();
        DefaultComboBoxModel mod = (DefaultComboBoxModel) wombo_combo.getModel();
        mod.removeAllElements();
        for (atma o : ap.getLista_atms()) {
            mod.addElement(o);
        }
    }

}
